-- MySQL Script generated by MySQL Workbench
-- Fri 17 Jan 2025 11:55:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema study_quiz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema study_quiz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `study_quiz` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `study_quiz` ;

-- -----------------------------------------------------
-- Table `study_quiz`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `study_quiz`.`user` (
  `id` INT NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `user_role` VARCHAR(45) NOT NULL,
  `user_created` VARCHAR(45) NOT NULL,
  `user_updated` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `userid_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `study_quiz`.`module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `study_quiz`.`module` (
  `id` INT NOT NULL,
  `module_name` VARCHAR(245) NOT NULL,
  `user_id` INT NOT NULL,
  `module_created` VARCHAR(45) NOT NULL,
  `user_updated` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `modulename_UNIQUE` (`module_name` ASC) VISIBLE,
  UNIQUE INDEX `moduleid_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `study_quiz`.`user` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `study_quiz`.`quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `study_quiz`.`quiz` (
  `id` INT NOT NULL,
  `quiz_name` VARCHAR(245) NOT NULL,
  `user_id` INT NOT NULL,
  `module_id` INT NOT NULL,
  `quiz_created` VARCHAR(45) NOT NULL,
  `user_updated` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_module_idx` (`id` ASC, `quiz_name` ASC) VISIBLE,
  INDEX `fk_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_module_idx1` (`module_id` ASC) VISIBLE,
  CONSTRAINT `fk_module_id_quiz`
    FOREIGN KEY (`module_id`)
    REFERENCES `study_quiz`.`module` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_id_quiz`
    FOREIGN KEY (`user_id`)
    REFERENCES `study_quiz`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `study_quiz`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `study_quiz`.`question` (
  `id` INT NOT NULL,
  `question_name` VARCHAR(500) NOT NULL,
  `module_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `quiz_id` INT NOT NULL,
  `questioncol` INT NOT NULL,
  `question_created` VARCHAR(45) NOT NULL,
  `question_updated` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `questionid_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `moduleid_UNIQUE` (`module_id` ASC) VISIBLE,
  UNIQUE INDEX `userid_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `quizid_UNIQUE` (`quiz_id` ASC) VISIBLE,
  CONSTRAINT `fk_module_question`
    FOREIGN KEY (`module_id`)
    REFERENCES `study_quiz`.`module` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_quiz`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `study_quiz`.`quiz` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_question`
    FOREIGN KEY (`user_id`)
    REFERENCES `study_quiz`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `study_quiz`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `study_quiz`.`answers` (
  `id` INT NOT NULL,
  `answer_name` VARCHAR(345) NOT NULL,
  `answer_correct` TINYINT NOT NULL,
  `user_id` INT NOT NULL,
  `module_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `quiz_id` INT NOT NULL,
  `attempt_created` VARCHAR(45) NOT NULL,
  `attempt_updated` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `answer_name_UNIQUE` (`answer_name` ASC) VISIBLE,
  UNIQUE INDEX `userid_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `module_id_UNIQUE` (`module_id` ASC) VISIBLE,
  UNIQUE INDEX `question_id_UNIQUE` (`question_id` ASC) VISIBLE,
  UNIQUE INDEX `quiz_id_UNIQUE` (`quiz_id` ASC) VISIBLE,
  CONSTRAINT `fk_moduleid_answer`
    FOREIGN KEY (`module_id`)
    REFERENCES `study_quiz`.`module` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_questionid_answer`
    FOREIGN KEY (`question_id`)
    REFERENCES `study_quiz`.`question` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_quizid_answer`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `study_quiz`.`module` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_userid_answer`
    FOREIGN KEY (`user_id`)
    REFERENCES `study_quiz`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `study_quiz`.`attempt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `study_quiz`.`attempt` (
  `id` INT NOT NULL,
  `attempt_score` INT NOT NULL,
  `user_id` INT NOT NULL,
  `module_id` INT NOT NULL,
  `quiz_id` INT NOT NULL,
  `attempt_date` DATETIME NOT NULL,
  `attempt_created` VARCHAR(45) NOT NULL,
  `attempt_updated` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `attemptid_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_userid_attempt_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_moduleid_attempt_idx` (`module_id` ASC) VISIBLE,
  CONSTRAINT `fk_moduleid_attempt`
    FOREIGN KEY (`module_id`)
    REFERENCES `study_quiz`.`module` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_quizid_attempt`
    FOREIGN KEY (`id`)
    REFERENCES `study_quiz`.`quiz` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_userid_attempt`
    FOREIGN KEY (`user_id`)
    REFERENCES `study_quiz`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `study_quiz`.`followup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `study_quiz`.`followup` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `module_id` INT NOT NULL,
  `quiz_id` INT NOT NULL,
  `followup_due_date` DATETIME NOT NULL,
  `is_completed` TINYINT NOT NULL,
  `followup_created` VARCHAR(45) NOT NULL,
  `followup_updated` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `followupid_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_userid_followup_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_moduleid_followup_idx` (`module_id` ASC) VISIBLE,
  INDEX `fk_quizid_followup_idx` (`quiz_id` ASC) VISIBLE,
  CONSTRAINT `fk_moduleid_followup`
    FOREIGN KEY (`module_id`)
    REFERENCES `study_quiz`.`module` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_quizid_followup`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `study_quiz`.`quiz` (`id`),
  CONSTRAINT `fk_userid_followup`
    FOREIGN KEY (`user_id`)
    REFERENCES `study_quiz`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
