"""Make ai_usage id auto increment

Revision ID: 25b1ffbc6660
Revises: 88e06c62efc8
Create Date: 2026-08-14 21:40:34.250798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25b1ffbc6660'
down_revision: Union[str, None] = '88e06c62efc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.execute("""
        DO $$
        BEGIN
            IF (
                SELECT column_default IS NULL
                FROM information_schema.columns
                WHERE table_name = 'ai_usage'
                  AND column_name = 'id'
            ) THEN
                ALTER TABLE ai_usage
                ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            END IF;
        END $$;
    """)

def downgrade() -> None:
    op.execute("""
        ALTER TABLE ai_usage
        ALTER COLUMN id DROP IDENTITY IF EXISTS
    """)
