name: FastAPI latency cold start
run-name: ${{ github.actor }} is measuring FastAPI backend response time

on: 
  schedule:
    - cron: "11,12,13,14 22 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run:
          bash observability/cold-start/script.sh
