name: FastAPI latency cold start
run-name: ${{ github.actor }} is measuring FastAPI backend response time

on:
  push:  
  #schedule:
  #  - cron: "07,08,09,10 22 * * *"

permissions: 
  contents: write
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Measure cold start
        run: bash script.sh
