name: Integration Tests
run-name: ${{ github.actor }} is running Integration tests

on: [push]

permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    environment : integration-tests
    strategy:
      matrix:
        python-version : ["3.10","3.11"]
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{matrix.python-version}}
          cache: pip
          cache-dependency-path: backend/requirements.txt
      
      - name: Install Python dependencies  
        run: pip3 install -r backend/requirements.txt
      - name: Install postgres + psql
        env:
          P1: ${{ secrets.P1}}
          P2: ${{ secrets.P2}}
          P3: ${{ secrets.P3}}
          TABLE_NAME : user
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql postgresql-client
          sudo systemctl start postgresql.service
          sudo -u postgres createdb test
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"
          sudo -u postgres psql -d test -f dbschema.sql
          sudo -u postgres psql -d test -c "INSERT INTO \"user\" (user_name, email, password, role, verified) VALUES ('testuser1', 'user1@gmail.com', '$P1', 'root', true);"
          sudo -u postgres psql -d test -c "INSERT INTO \"user\" (user_name, email, password, role, verified) VALUES ('testuser2', 'user2@gmail.com', '$P2', 'user', false);"
          sudo -u postgres psql -d test -c "INSERT INTO \"user\" (user_name, email, password, role, verified) VALUES ('test_user3', 'user3@gmail.com', '$P3', 'user', false);"
          sudo -u postgres psql -d test -c '\dt'
          sudo -u postgres psql -d test -c 'SELECT id, user_name, email, role, verified FROM "user";'
      - name: Test with pytest
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost/test
          TEST_DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost/test
          PYTHONPATH: backend
          SECRET_KEY: ${{ secrets.TEST_SECRET_KEY}}
          ALGORITHM: HS256
        run: |
          pip install pytest pytest-cov
          pytest backend/app/tests/test_user.py backend/app/tests/test_module.py \
            --doctest-modules \
            --junitxml=junit/test-results.xml \
            --cov=backend/app \
            --cov-report=xml \
            --cov-report=html
