name: Keep-Alive

on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  keep-server-awake:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the backend 
        run: wget https://studyquiz.onrender.com/health
