name: Keep-Alive

on:
  workflow_dispatch:
  schedule:
    - cron: '*/01 * * * *'
jobs:
  keep-server-awake:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the backend 
        run: wget -q -O /dev/null https://studyquiz.onrender.com/health
